config/routes.rb
Rails.application.routes.draw do
  resources :accounts do
    collection do
      get :profile
      get :qr_code
      get :classes
      get :past_classes
      get :packages
      get :past_packages
      get :admin
      get :autocomplete
      get :clear
      get :member
    end
  end
  resources :contents
  resources :purchases do
    collection do
      get :add
    end
  end
  resources :pages
  resources :class_registrations do
    collection do
      get :register
      get :roster
      get :attended
      get :cancel
      get :no_show
      get :submit
      get :paid
      get :qr_scan
    end
  end
  resources :instructors
  resources :studio_events
  resources :events
  resources :passes do
    collection do
      get :buy
      get :remove
    end
  end
  resources :locations
  devise_for :users
  resources :class_types
  get '/studio' => 'main#studio', as: 'studio'
  get '/faq' => 'main#faq', as: 'faq'
  get '/schedule' => 'main#schedule', as: 'schedule'
  # get '/account' => 'main#account', as: 'account'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount FullcalendarEngine::Engine => "/fullcalendar", as: 'fullcalendar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main#index'
end

app/models/class_registration.rb
class ClassRegistration < ApplicationRecord

  default_scope { order(id: :asc) }

  belongs_to :user
  belongs_to :class_type
  belongs_to :purchase

  def get_instructor
    event = FullcalendarEngine::Event.where(id: self.fullcalendar_engine_events_id).first
    if event.blank?
      return "Class Removed"
    else
      i = Instructor.where(id: event.instructor_id).first
      if i.blank?
        return "TBD"
      else
        return i.name
      end
    end
  end

  def get_class_type
    event = FullcalendarEngine::Event.where(id: self.fullcalendar_engine_events_id).first
    if event.blank?
      return "Class Removed"
    else
      return ClassType.find(event.class_type_id).name
    end
  end

  def get_class_date_time
    event = FullcalendarEngine::Event.where(id: self.fullcalendar_engine_events_id).first
    if event.blank?
      return "Class Removed"
    else
      return "#{event.starttime.to_datetime.strftime('%A %D')} - #{event.starttime.to_datetime.strftime('%I:%M %p')}"
    end
  end

  def can_cancel?
    event = FullcalendarEngine::Event.where(id: self.fullcalendar_engine_events_id).first
    if event.blank?
      return false
    else
      start_time = event.starttime
      cancel_time = start_time - 2.hours
      return Time.zone.now < cancel_time
    end
  end

end

app/controllers/class_registrations_controller.rb
class ClassRegistrationsController < ApplicationController

  before_action :check_waiver_date

  def check_waiver_date
    unless current_user.nil? || current_user.admin
      if current_user.waiver_date.nil? || current_user.waiver_date < Date.today - 1.year
        redirect_to edit_user_registration_path(waiver: false)
      end
    end
  end

  def register
    event_id = params[:event_id]
    @event = FullcalendarEngine::Event.find(event_id)
    @date = @event.starttime.to_datetime.strftime('%A %D')
    @stime = @event.starttime.to_datetime.strftime('%I:%M %p')
    @etime = @event.endtime.to_datetime.strftime('%I:%M %p')

    if !current_user.nil? && current_user.admin && !session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    elsif !current_user.nil? && !current_user.admin
      @user = current_user
    end

    unless @user.nil?
      @class_type = ClassType.find(@event.class_type_id)

      if ClassRegistration.where(user: @user, fullcalendar_engine_events_id: @event.id).blank?
        if params[:purchase_id]
          #user has selected the purchase to use
          cr = ClassRegistration.create(fullcalendar_engine_events_id: @event.id, class_type: @class_type, user: @user, class_date: @event.starttime, purchase: Purchase.find(params[:purchase_id]))
          p "Registered. A package was selected."
          redirect_to fullcalendar_path, :flash => {success: 'You have successfully registered for the class.'}
        else
          @current_packages = @user.find_valid_packages(@class_type, @event.starttime)
          if @current_packages.blank?
            p "No valid package."
            redirect_to fullcalendar_path, :flash => {danger: 'You do not have a valid package.'}
          elsif @current_packages.length == 1
            cr = ClassRegistration.create(fullcalendar_engine_events_id: @event.id, class_type: @class_type, user: @user, class_date: @event.starttime, purchase: @current_packages[0])
            p "Registered. Only one package available."
            redirect_to fullcalendar_path, :flash => {success: 'You have successfully registered for the class.'}
          elsif @current_packages.length > 1
            p "Choose package"
            #user needs to choose purchase
          end
        end
      else
        p "You are already registered for this class."
        redirect_to fullcalendar_path, :flash => {danger: 'You are already registered for this class.'}
      end
    end
  end

  def roster
    event_id = params[:event_id]
    @event = FullcalendarEngine::Event.find(event_id)
    @date = @event.starttime.to_datetime.strftime('%A %D')
    @class_registrations = ClassRegistration.where(fullcalendar_engine_events_id: @event.id)
    @reg_count = @class_registrations.length

    @mailto = "mailto:info@latinbeatstudio.com?bcc="
    @class_registrations.each do |cr|
      @mailto = @mailto + cr.user.email + ";"
    end
  end

  def cancel
    if params[:roster]
      @cr = ClassRegistration.find(params[:reg])
      @event = FullcalendarEngine::Event.find(@cr.fullcalendar_engine_events_id)
      if @cr.purchase.quantity_used < 2
        @cr.purchase.reset_expire
      end
      @cr.destroy
      @class_registrations = ClassRegistration.where(fullcalendar_engine_events_id: @event.id)
      respond_to do |format|
        format.js { }
      end
    else
      @cr = ClassRegistration.find(params[:reg])
      @cr.destroy
      redirect_to accounts_url, :flash => {success: 'You have successfully canceled your registration.'}
    end
  end

  def attended
    #if manually clicked from roster
    if params[:reg]
      reg = ClassRegistration.find(params[:reg])
      reg.update(attended: true)
      reg.update(no_show: false)
      if reg.purchase.expire.blank?
        Purchase.find(reg.purchase).set_expire
      end
      @event = FullcalendarEngine::Event.find(reg.fullcalendar_engine_events_id)
      @class_registrations = ClassRegistration.where(fullcalendar_engine_events_id: @event.id)
      respond_to do |format|
        format.js { }
      end
    end
  end

  def no_show
    #if manually clicked from roster
    if params[:reg]
      reg = ClassRegistration.find(params[:reg])
      reg.update(no_show: true)
      reg.update(attended: false)
      if reg.purchase.expire.blank?
        Purchase.find(reg.purchase).set_expire
      end
      @event = FullcalendarEngine::Event.find(reg.fullcalendar_engine_events_id)
      @class_registrations = ClassRegistration.where(fullcalendar_engine_events_id: @event.id)
      respond_to do |format|
        format.js { }
      end
    end
  end

  def paid
    #if manually clicked from roster
    if params[:reg]
      reg = ClassRegistration.find(params[:reg])
      if reg.purchase.paid
        Purchase.find(reg.purchase).update(paid: false)
      else
        Purchase.find(reg.purchase).update(paid: true)
      end
      @event = FullcalendarEngine::Event.find(reg.fullcalendar_engine_events_id)
      @class_registrations = ClassRegistration.where(fullcalendar_engine_events_id: @event.id)
      respond_to do |format|
        format.js { }
      end
    end
  end

  def submit
    #submit all no_shows
    event_id = params[:event_id]
    @event = FullcalendarEngine::Event.find(event_id)
    @class_registrations = ClassRegistration.where(fullcalendar_engine_events_id: event_id)

    @class_registrations.each do |reg|
      if !reg.attended
        reg.update(no_show: true)
        if reg.purchase.expire.blank?
          Purchase.find(reg.purchase).set_expire
        end
      end
    end
    respond_to do |format|
      format.js { }
    end
  end

  def qr_scan
    #if coming from QR code
    if params[:uid]
      @user = User.find(params[:uid])
      @event = FullcalendarEngine::Event.where("starttime > ?", (DateTime.now.in_time_zone("America/New_York").to_time - 30.minutes).to_datetime).order("starttime ASC").first
      reg = ClassRegistration.where(user: @user, fullcalendar_engine_events_id: @event.id).first
      @message = ""
      #if already registered for the class
      if reg
        reg.update(attended: true)
        reg.update(no_show: false)
        if reg.purchase.expire.blank?
          @pur = Purchase.find(reg.purchase)
          @pur.set_expire
        end
        @message = "#{@user.fullname} was marked as attended."

      else
        #if not registered for the class, register then mark as attended
        @class_type = ClassType.find(@event.class_type_id)
        @current_packages = @user.find_valid_packages(@class_type, @event.starttime)
        if @current_packages.blank?
          p "No valid package."
          @message = "#{@user.fullname} does not have a valid package for this class."
          return
        elsif @current_packages.length == 1
          cr = ClassRegistration.create(fullcalendar_engine_events_id: @event.id, class_type: @class_type, user: @user, class_date: @event.starttime, purchase: @current_packages[0])
          cr.update(attended: true)
          cr.update(no_show: false)
          if cr.purchase.expire.blank?
            @pur = Purchase.find(cr.purchase)
            @pur.set_expire
          end
          p "Registered. Only one package available."
          @message = "#{@user.fullname} was registered and marked as attended."
        elsif @current_packages.length > 1
          p "Choose package"
          @message = "Cannot register automatically. #{@user.fullname} has more than one valid package for this class."
        end
      end
    end
  end

end

app/views/class_registrations/attended.js.erb
// confirm file called
console.log("attended.js.erb file");

$(".tbody").html("");


<% @class_registrations.each do |r| %>
  $(".tbody").append("<tr>")
    <% unless r.user.first_name.blank? %>
      $(".tbody").append("<td><%= r.user.first_name %> <%= r.user.last_name %></td>")
    <% else %>
      $(".tbody").append("<td><%= r.user.username %></td>")
    <% end %>
    $(".tbody").append("<td><%= r.purchase.pass.name %></td>")
    $(".tbody").append("<td><%= r.purchase.quantity_available_display %></td>")
    $(".tbody").append("<td><%= r.purchase.get_expire_date %></td>")
    <% if r.purchase.paid %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.attended %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.no_show %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    $(".tbody").append("<td><%= escape_javascript link_to 'Cancel Reg', cancel_class_registrations_path(reg: r, roster: true), remote: true, class: 'btn btn-sm btn-info' %></td>")
  $(".tbody").append("</tr>")
<% end %>

app/views/class_registrations/cancel.js.erb
// confirm file called
console.log("cancel.js.erb file");

$(".tbody").html("");


<% @class_registrations.each do |r| %>
  $(".tbody").append("<tr>")
    <% unless r.user.first_name.blank? %>
      $(".tbody").append("<td><%= r.user.first_name %> <%= r.user.last_name %></td>")
    <% else %>
      $(".tbody").append("<td><%= r.user.username %></td>")
    <% end %>
    $(".tbody").append("<td><%= r.purchase.pass.name %></td>")
    $(".tbody").append("<td><%= r.purchase.quantity_available_display %></td>")
    $(".tbody").append("<td><%= r.purchase.get_expire_date %></td>")
    <% if r.purchase.paid %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.attended %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.no_show %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    $(".tbody").append("<td><%= escape_javascript link_to 'Cancel Reg', cancel_class_registrations_path(reg: r, roster: true), remote: true, class: 'btn btn-sm btn-info' %></td>")
  $(".tbody").append("</tr>")
<% end %>

app/views/class_registrations/no_show.js.erb
// confirm file called
console.log("no_show.js.erb file");

$(".tbody").html("");


<% @class_registrations.each do |r| %>
  $(".tbody").append("<tr>")
    <% unless r.user.first_name.blank? %>
      $(".tbody").append("<td><%= r.user.first_name %> <%= r.user.last_name %></td>")
    <% else %>
      $(".tbody").append("<td><%= r.user.username %></td>")
    <% end %>
    $(".tbody").append("<td><%= r.purchase.pass.name %></td>")
    $(".tbody").append("<td><%= r.purchase.quantity_available_display %></td>")
    $(".tbody").append("<td><%= r.purchase.get_expire_date %></td>")
    <% if r.purchase.paid %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.attended %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.no_show %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    $(".tbody").append("<td><%= escape_javascript link_to 'Cancel Reg', cancel_class_registrations_path(reg: r, roster: true), remote: true, class: 'btn btn-sm btn-info' %></td>")
  $(".tbody").append("</tr>")
<% end %>

app/views/class_registrations/paid.js.erb
// confirm file called
console.log("paid.js.erb file");

$(".tbody").html("");


<% @class_registrations.each do |r| %>
  $(".tbody").append("<tr>")
    <% unless r.user.first_name.blank? %>
      $(".tbody").append("<td><%= r.user.first_name %> <%= r.user.last_name %></td>")
    <% else %>
      $(".tbody").append("<td><%= r.user.username %></td>")
    <% end %>
    $(".tbody").append("<td><%= r.purchase.pass.name %></td>")
    $(".tbody").append("<td><%= r.purchase.quantity_available_display %></td>")
    $(".tbody").append("<td><%= r.purchase.get_expire_date %></td>")
    <% if r.purchase.paid %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.attended %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.no_show %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    $(".tbody").append("<td><%= escape_javascript link_to 'Cancel Reg', cancel_class_registrations_path(reg: r, roster: true), remote: true, class: 'btn btn-sm btn-info' %></td>")
  $(".tbody").append("</tr>")
<% end %>

app/views/class_registrations/qr_scan.html.erb
<div class="container">
  <div class="page-header">
    <h4><%= @message %></h4>
  </div>
</div> <!-- /container -->
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= @event.title %><br />
      <%= @event.starttime.to_datetime.strftime('%A %D - %I:%M %p') %><br />
      <% unless @pur.blank? %>
        Package:<%= @pur.pass.name %>, <%= @pur.quantity_available %> classes left.<br />
        Expires: <%= @pur.get_expire_date %><br />
        Paid? <%= @pur.paid %><br />
      <% end %>
      <% unless @current_packages.blank? %>
        <% @current_packages.each do |pur| %>
          <hr>
          Package:<%= pur.pass.name %>, <%= pur.quantity_available %> classes left.<br />
          Expires: <%= pur.get_expire_date %><br />
          Paid? <%= pur.paid %><br />
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/class_registrations/register.html.erb
<div class="container">
  <div class="page-header">
    <h1>Register for <%= @event.title %></h1>
  </div>
  <hr>
</div> <!-- /container -->

<div class="container">
  <% if user_signed_in? %>
    <% if @user.nil? %>
      oops... how did you get here?
    <% else %>
      <div class="row">
        <div class="col-md-3">
          <h3>Class Info</h3>
          Date: <%= @date %><br />
          Starting at: <%= @stime %><br />
          Ending at: <%= @etime %>
        </div>
        <div class="col-md-6">
          <h3>Select Package</h3>
          <p>You have more than one package on your account that fits this class. Please choose which package you would like to use.</p>
          <table class="table table-sm">
            <thead>
              <tr>
                <th>Package Name</th>
                <th>Purchase Date</th>
                <th>Expire Date</th>
                <th>Classes Availble</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @current_packages.each do |cp| %>
                <tr>
                  <td><%= cp.pass.name %></td>
                  <td><%= cp.created_at %></td>
                  <td><%= cp.expire %></td>
                  <td><%= cp.quantity_available_display %></td>
                  <td><%= link_to('Select', register_class_registrations_path(event_id: @event.id, purchase_id: cp.id), class: "btn btn-primary btn-md") %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  <% else %>
    oops... how did you get here?
  <% end %>
</div>

app/views/class_registrations/roster.html.erb
<div class="container">
  <div class="page-header">
    <h1>Roster for <%= @event.title %> <br /> <%= @date %></h1>
  </div>
  <hr>
</div> <!-- /container -->

<div class="container">
  <% if user_signed_in? %>
    <% if current_user.admin %>
      <p class="roster">
        <%= link_to "Submit Roster", submit_class_registrations_path(event_id: @event.id), remote: true, class: "btn btn-primary btn-lg" %>
        <a href="<%= @mailto %>" class="btn btn-primary btn-lg">Email Registered Members</a>
        <span class="total-reg">Total Registered: <%= @reg_count %></span>
      </p>
      <table class="table table-sm">
        <thead>
          <tr>
            <th>Member</th>
            <th>Curent Package</th>
            <th>Classes Left</th>
            <th>Expiration</th>
            <th>Paid?</th>
            <th>Attended?</th>
            <th>No Show?</th>
            <th></th>
          </tr>
        </thead>
        <tbody class="tbody">
          <% @class_registrations.each do |r| %>
            <tr>
              <td>
                <%= r.user.fullname %>
              </td>
              <td><%= r.purchase.pass.name %></td>
              <td><%= r.purchase.quantity_available %></td>
              <td><%= r.purchase.get_expire_date %></td>
              <% if r.purchase.paid %>
                <td><%= link_to "Yes", paid_class_registrations_path(reg: r), remote: true, class: "btn btn-sm btn-success" %></td>
              <% else %>
                <td><%= link_to "No", paid_class_registrations_path(reg: r), remote: true, class: "btn btn-sm btn-danger" %></td>
              <% end %>
              <% if r.attended %>
                <td><%= link_to "Yes", attended_class_registrations_path(reg: r), remote: true, class: "btn btn-sm btn-success" %></td>
              <% else %>
                <td><%= link_to "No", attended_class_registrations_path(reg: r), remote: true, class: "btn btn-sm btn-danger" %></td>
              <% end %>
              <% if r.no_show %>
                <td><%= link_to "Yes", no_show_class_registrations_path(reg: r), remote: true, class: "btn btn-sm btn-success" %></td>
              <% else %>
                <td><%= link_to "No", no_show_class_registrations_path(reg: r), remote: true, class: "btn btn-sm btn-danger" %></td>
              <% end %>
              <td><%= link_to "Cancel Reg", cancel_class_registrations_path(reg: r, roster: true), remote: true, class: "btn btn-sm btn-info" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% else %>
    Sorry, you're not supposed to be here.
  <% end %>
</div>

app/views/class_registrations/submit.js.erb
// confirm file called
console.log("submit.js.erb file");

$(".tbody").html("");


<% @class_registrations.each do |r| %>
  $(".tbody").append("<tr>")
    <% unless r.user.first_name.nil? %>
      $(".tbody").append("<td><%= r.user.first_name %> <%= r.user.last_name %></td>")
    <% else %>
      $(".tbody").append("<td><%= r.user.username %></td>")
    <% end %>
    $(".tbody").append("<td><%= r.purchase.pass.name %></td>")
    $(".tbody").append("<td><%= r.purchase.quantity_available_display %></td>")
    $(".tbody").append("<td><%= r.purchase.get_expire_date %></td>")
    <% if r.purchase.paid %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', paid_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.attended %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', attended_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    <% if r.no_show %>
      $(".tbody").append("<td><%= escape_javascript link_to 'Yes', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-success' %></td>")
    <% else %>
      $(".tbody").append("<td><%= escape_javascript link_to 'No', no_show_class_registrations_path(reg: r), remote: true, class: 'btn btn-sm btn-danger' %></td>")
    <% end %>
    $(".tbody").append("<td><%= escape_javascript link_to 'Cancel Reg', cancel_class_registrations_path(reg: r, roster: true), remote: true, class: 'btn btn-sm btn-info' %></td>")
  $(".tbody").append("</tr>")
<% end %>