config/routes.rb
Rails.application.routes.draw do
  resources :accounts do
    collection do
      get :profile
      get :qr_code
      get :classes
      get :past_classes
      get :packages
      get :past_packages
      get :admin
      get :autocomplete
      get :clear
      get :member
    end
  end
  resources :contents
  resources :purchases do
    collection do
      get :add
    end
  end
  resources :pages
  resources :class_registrations do
    collection do
      get :register
      get :roster
      get :attended
      get :cancel
      get :no_show
      get :submit
      get :paid
      get :qr_scan
    end
  end
  resources :instructors
  resources :studio_events
  resources :events
  resources :passes do
    collection do
      get :buy
      get :remove
    end
  end
  resources :locations
  devise_for :users
  resources :class_types
  get '/studio' => 'main#studio', as: 'studio'
  get '/faq' => 'main#faq', as: 'faq'
  get '/schedule' => 'main#schedule', as: 'schedule'
  # get '/account' => 'main#account', as: 'account'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount FullcalendarEngine::Engine => "/fullcalendar", as: 'fullcalendar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main#index'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    if !session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    @class_registrations = @user.class_registrations.order(class_date: :asc)
    @purchases = @user.current_purchases
    @qrcode = RQRCode::QRCode.new("#{root_url}class_registrations/qr_scan?uid=#{@user.id}")
    @png = @qrcode.as_png.to_image.resize(400,400).to_data_url
  end

  def profile
    unless session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    respond_to do |format|
      format.js { }
    end
  end

  def qr_code
    unless session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    @qrcode = RQRCode::QRCode.new("#{root_url}class_registrations/qr_scan?uid=#{@user.id}")
    @png = @qrcode.as_png.to_image.resize(400,400).to_data_url
    respond_to do |format|
      format.js { }
    end
  end

  def classes
    unless session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    @class_registrations = @user.class_registrations.where('class_date > ?', DateTime.now.in_time_zone("America/New_York")).order(class_date: :asc)
    respond_to do |format|
      format.js { }
    end
  end

  def past_classes
    unless session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    @class_registrations = @user.class_registrations.where('class_date < ?', DateTime.now.in_time_zone("America/New_York")).order(class_date: :desc)
    respond_to do |format|
      format.js { }
    end
  end

  def packages
    unless session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    if !params[:suspend].blank?
      package = Purchase.find(params[:pkg])
      package.suspend = params[:suspend]
      if params[:suspend] == "true"
        package.remaining_days = ((package.expire - Time.now) / 1.day).to_i
        package.suspend_start = Time.now
        package.class_registrations.where("class_date > ?", Time.now).delete_all
      elsif params[:suspend] == "false"
        package.suspend_end = Time.now
        package.expire = Time.now + (package.remaining_days + 1).days
      end
      package.save
    end

    if !params[:purchase].blank?
      purchase = Purchase.find(params[:purchase])
      if purchase.paid
        purchase.update(paid: false)
      else
        purchase.update(paid: true)
      end
      purchase.save
    end
    @purchases = @user.current_purchases
    respond_to do |format|
      format.js { }
    end
  end

  def past_packages
    unless session[:member_selected].blank?
      @user = User.find(session[:member_selected])
    else
      @user = current_user
    end
    @past_purchases = @user.past_purchases
    respond_to do |format|
      format.js { }
    end
  end

  def admin
    puts "in admin method"
    @today = User.where("EXTRACT(DAY FROM birthday) = ? AND EXTRACT(MONTH FROM birthday) = ?", Date.today.day, Date.today.month)
    @this_month = User.where("EXTRACT(DAY FROM birthday) >= ? AND EXTRACT(DAY FROM birthday) <= ? AND EXTRACT(MONTH FROM birthday) = ?", Date.today.day, 30, Date.today.month)
  end

  def member
    if !params[:query_id].blank? && params[:query_id].to_i > 0
      if !params[:query].blank? && params[:query].include?("(")
        @user = User.find(params[:query_id])
        session[:member_selected] = @user.id
        @message = "#{@user.username.capitalize} Selected"
      elsif !params[:query].blank?
        @results = User.where("lower(username) LIKE :query OR lower(first_name) LIKE :query OR lower(last_name) LIKE :query", query: "%#{params[:query].downcase}%")
        if @results.count > 0
          @message = "Please Choose Member"
        else
          @user = current_user
          @message = "No Member Found"
        end
      else
        @message = "No Query Submitted"
      end
    elsif !params[:query].blank?
      @results = User.where("lower(username) LIKE :query OR lower(first_name) LIKE :query OR lower(last_name) LIKE :query", query: "%#{params[:query].downcase}%")
      if @results.count > 0
        @message = "Please Choose Member"
      else
        @user = current_user
        @message = "No Member Found"
      end
    else
      @message = "No Query Submitted"
    end
    respond_to do |format|
      format.js { }
    end
  end

  def clear
    session[:member_selected] = nil
    redirect_to root_path
    puts "cleared member selected"
  end

  def autocomplete
    @users = User.order(:username).where("lower(username) LIKE ? or lower(first_name) LIKE ? or lower(last_name) LIKE ?", "%#{params[:term].downcase}%", "%#{params[:term].downcase}%", "%#{params[:term].downcase}%")
    respond_to do |format|
      format.html
      format.json {
        render json: @users.map { |u| { :label => u.autocomplete_name, :value => u.id } }.to_json
      }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/admin.html.erb
<div class="container">
  <div class="page-header">
    <h1>Member Account Administration</h1>
  </div>
  <hr>
</div> <!-- /container -->

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <p>
        Start typing username, first name or last name to search.
        <br /><br />
      </p>
    </div>
    <div class="col-md-6">
      <%= form_tag(member_accounts_path, method: "get", remote: true) do %>
        <div class="row">
          <div class="col-md-8">
            <%= text_field_tag :query, params[:query], id: "search-input", class: 'form-control', placeholder: 'Start typing member name...' %>
            <%= hidden_field_tag :query_id %>
          </div>
          <div class="col-md-2">
            <%= submit_tag("Go", :class => "btn btn-primary btn-md") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="choose-member"></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h2>Upcoming Birthdays</h2>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-6">
      <div class="birthdays">
        <h4>Today</h4>
        <% unless @today.blank? %>
          <% @today.each do |t| %>
            <%= t.fullname %> - <%= t.birthday.to_datetime.strftime('%D') %><br />
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="birthdays">
        <h4>This Month</h4>
        <% unless @this_month.blank? %>
          <% @this_month.each do |t| %>
            <%= t.fullname %> - <%= t.birthday.to_datetime.strftime('%D') %><br />
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>

var ready;
ready = (function() {
  $("#query_id").val('');
  $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
  $("#search-input").autocomplete({
    source: '/accounts/autocomplete.json',
    select: function(event, ui) {
      $("#search-input").val(ui.item.label)
      $('#query_id').val(ui.item.value)
			return false;
		}
  });
});

$("#search-input").blur(function() {
  if (this.value == '') {
    $("#query_id").val('');
  }
});

$(document).ready(ready);
$(document).on('page:load', ready);

</script>

app/views/accounts/classes.js.erb
// confirm file called
console.log("classes.js.erb file");

$(".account-info").html("");

var str = ""

str = str + "<h3>Upcoming Registered Classes</h3>"
str = str + "<p><%= escape_javascript link_to('Register for a Class', fullcalendar_path, class: 'btn btn-primary btn-lg') %> &nbsp;&nbsp;&nbsp; <%= escape_javascript link_to('View Past Classes', past_classes_accounts_path, remote: true, class: 'btn btn-outline-primary btn-md') %></p>"
str = str + "<table class='table table-sm'><thead><tr><th>Date - Time</th><th>Class</th><th>Instructor</th><th></th></tr></thead><tbody>"
    <% @class_registrations.each do |r| %>
      str = str + "<tr><td><%= r.get_class_date_time %></td><td><%= r.get_class_type %></td><td><%= r.get_instructor %></td><td>"
        <% if r.can_cancel? %>
          str = str + "<%= escape_javascript link_to 'Cancel', cancel_class_registrations_path(reg: r) %>"
        <% else %>
          str = str + "Please call the studio to cancel."
        <% end %>
        str = str + "</td></tr>"
    <% end %>
  str = str + "</tbody></table>"

$(".account-info").html(str);

app/views/accounts/index.html.erb
<div class="container">
  <div class="page-header">
    <% if !@message.blank? %>
      <h1><%= @message %></h1>
    <% elsif !@user.fullname.blank? %>
      <h1><%= @user.fullname %>'s Account</h1>
    <% else %>
      <h1><%= @user.username.capitalize %>'s Account</h1>
    <% end %>
  </div>
  <hr>
</div> <!-- /container -->

<div class="container account">
  <% if @message.blank? %>
    <% if user_signed_in? %>
      <div class="account-links">
        <%= link_to('Profile', profile_accounts_path(), remote: true, class: "btn btn-outline-primary btn-lg") %>
        <%= link_to('QR Code', qr_code_accounts_path(), remote: true, class: "btn btn-outline-primary btn-lg") %>
        <%= link_to('Classes', classes_accounts_path(), remote: true, class: "btn btn-outline-primary btn-lg") %>
        <%= link_to('Packages', packages_accounts_path(), remote: true, class: "btn btn-outline-primary btn-lg") %>
      </div>
      <div class="account-info">
        <h3>QR Code</h3>
        <div class='row'>
          <div class='qr'>
            <p>To save QR code, right click (or tap and hold on iPhone) and save image.</p>
            <%= image_tag(@png) %>
          </div>
        </div>
    <% else %>
      anonymous
    <% end %>
  <% else %>
    <div class="account-links">
      <%= link_to('Back to Manage Members', admin_accounts_path, class: "btn btn-primary btn-lg") %>
    </div>
  <% end %>
</div>

app/views/accounts/member.js.erb
// confirm file called
console.log("member.js.erb file");

$(".choose-member").html("");

var str = ""
str = str + "<h2><%=@message%></h2>"

<% if session[:member_selected] %>
  str = str + "<p><%= escape_javascript link_to 'Go to Account', accounts_path %></p><br />"
<% else %>
  <% @results.each do |r| %>
    str = str + "<%= escape_javascript link_to r.autocomplete_name, member_accounts_path(query_id: r.id, query: r.autocomplete_name), remote: true %><br />"
  <% end %>
  str = str + "<br />"
<% end %>

$(".choose-member").html(str);

app/views/accounts/packages.js.erb
// confirm file called
console.log("packages.js.erb file");

$(".account-info").html("");

var str = ""

str = str + "<h3>Current Packages</h3>"
str = str + "<p><%= escape_javascript link_to('Purchase Packages', passes_path(u: @user.id), class: 'btn btn-primary btn-lg') %> &nbsp;&nbsp;&nbsp; <%= escape_javascript link_to('View Past Packages', past_packages_accounts_path, remote: true, class: 'btn btn-outline-primary btn-md') %></p>"
str = str + "<table class='table table-sm'><thead><tr><th>Purchase Date</th><th>Package</th><th>Classes Remaining</th><th>Expire Date</th><th>Paid?</th><th>Suspend</th><th></th></tr></thead><tbody>"
<% @purchases.each do |o| %>
  str = str + "<tr><td><%= o.get_purchase_date %></td><td><%= o.pass.name %></td><td><%= o.quantity_available %></td>"
  <% if o.get_expire_date.blank? %>
    str = str + "<td>Not Set</td>"
  <% else %>
    str = str + "<td><%= o.get_expire_date %></td>"
  <% end %>

  <% if current_user.admin && !session[:member_selected].blank? %>
    <% if o.paid %>
      str = str + "<td><%= escape_javascript link_to 'Yes', packages_accounts_path(purchase: o), remote: true, class: 'btn btn-sm btn-success' %></td>"
    <% else %>
      str = str + "<td><%= escape_javascript link_to 'No', packages_accounts_path(purchase: o), remote: true, class: 'btn btn-sm btn-danger' %></td>"
    <% end %>
  <% else %>
    <% if o.paid %>
      str = str + "<td>Yes</td>"
    <% else %>
      str = str + "<td>No</td>"
    <% end %>
  <% end %>

  <% if o.suspend? && !o.suspend_start.blank? %>
    str = str + "<td><%= escape_javascript link_to 'Turn Off', packages_accounts_path(pkg: o, suspend: false), remote: true, class: 'btn btn-sm btn-danger', :data => {:confirm => 'Your package has been unsuspended. Please remember: You will need to re-register for any classes you previously had scheduled. Please hit CANCEL if you want to keep your package suspended.'} %></td>"
  <% elsif !o.expire.blank? && o.suspend_start.blank? %>
    str = str + "<td><%= escape_javascript link_to 'Turn On', packages_accounts_path(pkg: o, suspend: true), remote: true, class: 'btn btn-sm btn-success', :data => {:confirm => 'You are suspending this package from use. Please note: Any classes registered for from today into the future will be removed. You will need to re-register for classes after you unsuspend your package. Please hit CANCEL if you do NOT want to proceed.'} %></td>"
  <% else %>
    str = str + "<td>N/A</td>"
  <% end %>

  <% if o.can_remove? %>
    str = str + "<td><%= escape_javascript link_to('Remove This Package', remove_passes_path(p: o.id, a: true), class: 'btn btn-danger btn-sm') %></td>"
  <% end %>
  str = str + "</tr>"
<% end %>
str = str + "</tbody></table>"

$(".account-info").html(str);

app/views/accounts/past_classes.js.erb
// confirm file called
console.log("past_classes.js.erb file");

$(".account-info").html("");

var str = ""

str = str + "<h3>Past Registered Classes</h3>"
str = str + "<p><%= escape_javascript link_to('Register for a Class', fullcalendar_path, class: 'btn btn-primary btn-lg') %> &nbsp;&nbsp;&nbsp; <%= escape_javascript link_to('View Upcoming Classes', classes_accounts_path, remote: true, class: 'btn btn-outline-primary btn-md') %></p>"
str = str + "<table class='table table-sm'><thead><tr><th>Date - Time</th><th>Class</th><th>Instructor</th><th></th></tr></thead><tbody>"
    <% @class_registrations.each do |r| %>
      str = str + "<tr><td><%= r.get_class_date_time %></td><td><%= r.get_class_type %></td><td><%= r.get_instructor %></td><td>"
        <% if r.attended? %>
          str = str + "Attended"
        <% elsif r.no_show? %>
          str = str + "No Show"
        <% else %>
          str = str + "Attendance not Marked"  
        <% end %>
        str = str + "</td></tr>"
    <% end %>
  str = str + "</tbody></table>"

$(".account-info").html(str);

app/views/accounts/past_packages.js.erb
// confirm file called
console.log("past_packages.js.erb file");

$(".account-info").html("");

var str = ""

str = str + "<h3>Past Packages</h3>"
str = str + "<p><%= escape_javascript link_to('Purchase Packages', passes_path(u: @user.id), class: 'btn btn-primary btn-lg') %> &nbsp;&nbsp;&nbsp; <%= escape_javascript link_to('View Current Packages', packages_accounts_path, remote: true, class: 'btn btn-outline-primary btn-md') %></p>"
str = str + "<table class='table table-sm'><thead><tr><th>Purchase Date</th><th>Package</th><th>Classes Remaining</th><th>Expire Date</th><th>Paid?</th></tr></thead><tbody>"
<% @past_purchases.each do |o| %>
  str = str + "<tr><td><%= o.get_purchase_date %></td><td><%= o.pass.name %></td><td><%= o.quantity_available %></td>"
  <% if o.get_expire_date.blank? %>
    str = str + "<td>Not Set</td>"
  <% else %>
    str = str + "<td><%= o.get_expire_date %></td>"
  <% end %>
  <% if o.paid? %>
    str = str + "<td>Yes</td>"
  <% else %>
    str = str + "<td>No</td>"
  <% end %>
  str = str + "</tr>"
<% end %>
str = str + "</tbody></table>"

$(".account-info").html(str);

app/views/accounts/profile.js.erb
// confirm file called
console.log("profile.js.erb file");

$(".account-info").html("");

var str = ""
str = str + "<div class='row'>"
str = str + "<div class='col-md-3'><h3>Profile Info</h3></div>"
<% unless current_user.admin? %>
  str = str + "<div class='col-md-9'><%= escape_javascript link_to('Edit Profile', edit_user_registration_path, class: 'btn btn-primary btn-sm') %><br /><br /></div>"
<% end %>
str = str + "</div>"

str = str + "<div class='container'>"
  str = str + "<div class='row'>"
    str = str + "<div class='col-md-6'>"
      str = str + "Username: <%= @user.username %> <br />"
      str = str + "Email: <%= @user.email %> <br />"
      str = str + "Birthday: <%= @user.birthday %>"
    str = str + "</div>"

    str = str + "<div class='col-md-6'>"
      str = str + "First Name: <%= @user.first_name %> <br />"
      str = str + "Last Name: <%= @user.last_name %> <br />"
      str = str + "Mobile Phone: <%= @user.phone %>"
    str = str + "</div>"
  str = str + "</div>"
  str = str + "<hr />"
  str = str + "<div class='row'>"
    str = str + "<div class='col-md-6'>"
      str = str + "Address: <%= @user.address1 %> <br />"
      str = str + "Apt/Unit: <%= @user.address2 %>"
    str = str + "</div>"
    str = str + "<div class='col-md-6'>"
      str = str + "City: <%= @user.city %> <br />"
      str = str + "State: <%= @user.state %> <br />"
      str = str + "Zip: <%= @user.zip %>"
    str = str + "</div>"
  str = str + "</div>"
  str = str + "<hr />"
  str = str + "<div class='row'>"
    str = str + "<div class='col-md-6'>"
      str = str + "Emergency Contact Name: <%= @user.emergency_contact_name %>"
    str = str + "</div>"
    str = str + "<div class='col-md-6'>"
      str = str + "Emergency Contact Phone: <%= @user.emergency_contact_phone %>"
    str = str + "</div>"
  str = str + "</div>"
str = str + "</div>"

$(".account-info").html(str);

app/views/accounts/qr_code.js.erb
// confirm file called
console.log("qr_code.js.erb file");

$(".account-info").html("");

var str = ""
str = str + "<h3>QR Code</h3>"

str = str + "<div class='row'>"
  str = str + "<div class='qr'>"
    str = str + "<p>To save QR code, right click (or tap and hold on iPhone) and save image.</p>"
    str = str + "<%= escape_javascript image_tag(@png) %>"
  str = str + "</div>"
str = str + "</div>"

$(".account-info").html(str);